export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"

export const LOGIN_TO_ADMIN_REQUEST = "LOGIN_TO_ADMIN_REQUEST";
export const LOGIN_TO_ADMIN_SUCCESS = "LOGIN_TO_ADMIN_SUCCESS";
export const LOGIN_TO_ADMIN_FAILURE = "LOGIN_TO_ADMIN_FAILURE";