export const GET_DATA_PAINTING_REQUEST = "GET_DATA_PAINTING_REQUEST"
export const GET_DATA_PAINTING_SUCCESS = "GET_DATA_PAINTING_SUCCESS"
export const GET_DATA_PAINTING_FAILURE = "GET_DATA_PAINTING_FAILURE"

export const GET_HOME_DATA_REQUEST1 = "GET_HOME_DATA_REQUEST1"
export const GET_HOME_DATA_SUCCESS1 = "GET_HOME_DATA_SUCCESS1"
export const GET_HOME_DATA_FAILURE1 = "GET_HOME_DATA_FAILURE1"

export const GET_MENS_DATA_REQUEST2 = "GET_MENS_DATA_REQUEST2"
export const GET_MENS_DATA_SUCCESS2 = "GET_MENS_DATA_SUCCESS2"
export const GET_MENS_DATA_FAILURE2 = "GET_MENS_DATA_FAILURE2"

export const GET_WOMENS_DATA_REQUEST3 = "GET_WOMENS_DATA_REQUEST3"
export const GET_WOMENS_DATA_SUCCESS3 = "GET_WOMENS_DATA_SUCCESS3"
export const GET_WOMENS_DATA_FAILURE3 = "GET_WOMENS_DATA_FAILURE3"

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST"
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS"
export const ADD_NEW_PRODUCT_FAILURE = "ADD_NEW_PRODUCT_FAILURE"

export const ADMIN_PAGE_PRODUCT_REQUEST = "ADMIN_PAGE_NEW_PRODUCT_REQUEST"
export const ADMIN_PAGE_PRODUCT_SUCCESS = "ADMIN_PAGE_NEW_PRODUCT_SUCCESS"
export const ADMIN_PAGE_PRODUCT_FAILURE = "ADMIN_PAGE_NEW_PRODUCT_FAILURE"

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";