// Datas at home page
export const GET_HOME_DATA_REQUEST1 = "GET_HOME_DATA_REQUEST1"
export const GET_HOME_DATA_SUCCESS1 = "GET_HOME_DATA_SUCCESS1"
export const GET_HOME_DATA_FAILURE1 = "GET_HOME_DATA_FAILURE1"

// Datas at painting page
export const GET_DATA_PAINTING_REQUEST = "GET_DATA_PAINTING_REQUEST"
export const GET_DATA_PAINTING_SUCCESS = "GET_DATA_PAINTING_SUCCESS"
export const GET_DATA_PAINTING_FAILURE = "GET_DATA_PAINTING_FAILURE"

// Datas at mens page
export const GET_MENS_DATA_REQUEST2 = "GET_MENS_DATA_REQUEST2"
export const GET_MENS_DATA_SUCCESS2 = "GET_MENS_DATA_SUCCESS2"
export const GET_MENS_DATA_FAILURE2 = "GET_MENS_DATA_FAILURE2"

// Datas at womens page
export const GET_WOMENS_DATA_REQUEST3 = "GET_WOMENS_DATA_REQUEST3"
export const GET_WOMENS_DATA_SUCCESS3 = "GET_WOMENS_DATA_SUCCESS3"
export const GET_WOMENS_DATA_FAILURE3 = "GET_WOMENS_DATA_FAILURE3"

// adding new data to the home page as well as to admin page by admin
export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST"
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS"
export const ADD_NEW_PRODUCT_FAILURE = "ADD_NEW_PRODUCT_FAILURE"

// to get the data available at main page that is home page at admins space
export const ADMIN_PAGE_PRODUCT_REQUEST = "ADMIN_PAGE_NEW_PRODUCT_REQUEST"
export const ADMIN_PAGE_PRODUCT_SUCCESS = "ADMIN_PAGE_NEW_PRODUCT_SUCCESS"
export const ADMIN_PAGE_PRODUCT_FAILURE = "ADMIN_PAGE_NEW_PRODUCT_FAILURE"

// edit the data from admin page
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

// Adding data to cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

// get the datas which is available at cart
export const GET_DATA_FROM_CART_REQUEST = "GET_DATA_FROM_CART_REQUEST"
export const GET_DATA_FROM_CART_SUCCESS = "GET_DATA_FROM_CART_SUCCESS"
export const GET_DATA_FROM_CART_FAILURE = "GET_DATA_FROM_CART_FAILURE"

// delete the item present in cart
export const DELETE_THE_CART_ITEM_REQUEST = "DELETE_THE_CART_ITEM_REQUEST"
export const DELETE_THE_CART_ITEM_SUCCESS = "DELETE_THE_CART_ITEM_SUCCESS"
export const DELETE_THE_CART_ITEM_FAILURE = "DELETE_THE_CART_ITEM_FAILURE"

// get singleData Home
export const GET_SINGLE_DATA_REQUEST = "GET_SINGLE_DATA_REQUEST"
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS"
export const GET_SINGLE_DATA_FAILURE = "GET_SINGLE_DATA_FAILURE"

// get singleData MENS
export const GET_SINGLE_DATA_MEN_REQUEST = "GET_SINGLE_DATA_MEN_REQUEST"
export const GET_SINGLE_DATA_MEN_SUCCESS = "GET_SINGLE_DATA_MEN_SUCCESS"
export const GET_SINGLE_DATA_MEN_FAILURE = "GET_SINGLE_DATA_MEN_FAILURE"

// get singleData WOMENS
export const GET_SINGLE_DATA_WOMEN_REQUEST = "GET_SINGLE_DATA_WOMEN_REQUEST"
export const GET_SINGLE_DATA_WOMEN_SUCCESS = "GET_SINGLE_DATA_WOMEN_SUCCESS"
export const GET_SINGLE_DATA_WOMEN_FAILURE = "GET_SINGLE_DATA_WOMEN_FAILURE"

// get singleData WOMENS
export const GET_SINGLE_DATA_PAINT_REQUEST = "GET_SINGLE_DATA_PAINT_REQUEST"
export const GET_SINGLE_DATA_PAINT_SUCCESS = "GET_SINGLE_DATA_PAINT_SUCCESS"
export const GET_SINGLE_DATA_PAINT_FAILURE = "GET_SINGLE_DATA_PAINT_FAILURE"


// User details ADD and Get part
export const ADD_DATA_SHOP_CUSTOMER_REQUEST = 'ADD_DATA_SHOP_CUSTOMER_REQUEST'
export const ADD_DATA_SHOP_CUSTOMER_SUCCESS = 'ADD_DATA_SHOP_CUSTOMER_SUCCESS'
export const ADD_DATA_SHOP_CUSTOMER_FAILURE = 'ADD_DATA_SHOP_CUSTOMER_FAILURE'

export const GET_DATA_SHOP_CUSTOMER_REQUEST = 'GET_DATA_SHOP_CUSTOMER_REQUEST'
export const GET_DATA_SHOP_CUSTOMER_SUCCESS = 'GET_DATA_SHOP_CUSTOMER_SUCCESS'
export const GET_DATA_SHOP_CUSTOMER_FAILURE = 'GET_DATA_SHOP_CUSTOMER_FAILURE'


export const ADD_DATA_HOME_CUSTOMER_REQUEST = 'ADD_DATA_HOME_CUSTOMER_REQUEST'
export const ADD_DATA_HOME_CUSTOMER_SUCCESS = 'ADD_DATA_HOME_CUSTOMER_SUCCESS'
export const ADD_DATA_HOME_CUSTOMER_FAILURE = 'ADD_DATA_HOME_CUSTOMER_FAILURE'

export const GET_DATA_HOME_CUSTOMER_REQUEST = 'GET_DATA_HOME_CUSTOMER_REQUEST'
export const GET_DATA_HOME_CUSTOMER_SUCCESS = 'GET_DATA_HOME_CUSTOMER_SUCCESS'
export const GET_DATA_HOME_CUSTOMER_FAILURE = 'GET_DATA_HOME_CUSTOMER_FAILURE'

export const EDIT_STATUS_HOME_REQUEST = 'EDIT_STATUS_HOME_REQUEST'
export const EDIT_STATUS_HOME_SUCCESS = 'EDIT_STATUS_HOME_SUCCESS'
export const EDIT_STATUS_HOME_FAILURE = 'EDIT_STATUS_HOME_FAILURE'

export const EDIT_STATUS_SHOP_REQUEST = 'EDIT_STATUS_SHOP_REQUEST'
export const EDIT_STATUS_SHOP_SUCCESS = 'EDIT_STATUS_SHOP_SUCCESS'
export const EDIT_STATUS_SHOP_FAILURE = 'EDIT_STATUS_SHOP_FAILURE'

// // Adding data to wishList
export const ADD_TO_WISH_REQUEST = "ADD_TO_WISH_REQUEST"
export const ADD_TO_WISH_SUCCESS = "ADD_TO_WISH_SUCCESS"
export const ADD_TO_WISH_FAILURE = "ADD_TO_WISH_FAILURE"

// get the datas which is available at wishList
export const GET_DATA_FROM_WISH_REQUEST = "GET_DATA_FROM_WISH_REQUEST"
export const GET_DATA_FROM_WISH_SUCCESS = "GET_DATA_FROM_WISH_SUCCESS"
export const GET_DATA_FROM_WISH_FAILURE = "GET_DATA_FROM_WISH_FAILURE"

// delete the item present in wishList
export const DELETE_THE_WISH_ITEM_REQUEST = "DELETE_THE_WISH_ITEM_REQUEST"
export const DELETE_THE_WISH_ITEM_SUCCESS = "DELETE_THE_WISH_ITEM_SUCCESS"
export const DELETE_THE_WISH_ITEM_FAILURE = "DELETE_THE_WISH_ITEM_FAILURE"